import React,{useEffect,useState} from 'react';
import DitherVeil from './components/DitherVeil.jsx';
import ElectricBorder from './components/ElectricBorder.jsx';
import LogoLoop from './components/LogoLoop.jsx';
import GhostCursor from './components/GhostCursor.jsx';
import CircularCarousel from './components/CircularCarousel.jsx';
import {ArrowUpRight,ArrowRight,Code,Globe,Database,Mail,Menu,Github,Flash,ShoppingBag} from 'iconoir-react';
const projects=[
{title:'SIDOKA × INTACTOZ',subtitle:'Experiência editorial / Streetwear',src:'https://images.unsplash.com/photo-1523398002811-999ca8dec234?w=1000&q=85',href:'https://intactoz-underground.contamateusfortnite.com/'},
{title:'ROSE FREITAS',subtitle:'Produtos / Comunidade / Website',src:'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1000&q=85',href:'https://rosefreitas.com/'},
{title:'ARCEUZ',subtitle:'Plataforma e ferramentas digitais',src:'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1000&q=85',href:'https://github.com/ZenithWe'},
{title:'RESENHA MORUMBI',subtitle:'Eventos / Painel de gestão',src:'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=1000&q=85',href:'https://github.com/ZenithWe/camarote-resenha-morumbi'}];
const services=[['Websites Premium','Sites com identidade única, rápidos e responsivos.',Globe],['Landing Pages','Páginas de apresentação e conversão.',ArrowUpRight],['Painéis e Sistemas','Dashboards, áreas de usuários e ferramentas.',Database],['E-commerce','Catálogos, produtos e experiências de compra.',ShoppingBag],['Experiências Visuais','Efeitos, microinterações e interfaces memoráveis.',Flash],['Soluções Personalizadas','Sistemas construídos para seu negócio.',Code]];
const skills=['React','Next.js','JavaScript','HTML / CSS','Tailwind CSS','GSAP','Three.js','Supabase','Vercel','GitHub'];
export default function App(){const[menu,setMenu]=useState(false);const[light,setLight]=useState(true);const[mobile,setMobile]=useState(false);
useEffect(()=>{const m=window.matchMedia('(max-width: 750px), (prefers-reduced-motion: reduce)');const cb=()=>setMobile(m.matches);cb();m.addEventListener('change',cb);return()=>m.removeEventListener('change',cb)},[]);
return <><header><div className="container nav"><a className="brand" href="#home">MF<span>.</span>DEV</a><button className="menuButton" onClick={()=>setMenu(!menu)} aria-label="Abrir menu" aria-expanded={menu}><Menu/></button><nav className={menu?'open':''}>{[['Sobre','#sobre'],['Serviços','#servicos'],['Projetos','#projetos'],['Tecnologias','#stack']].map(([label,url])=><a onClick={()=>setMenu(false)} key={url} href={url}>{label}</a>)}<a onClick={()=>setMenu(false)} href="#contato" className="navcontact">Vamos conversar <ArrowUpRight width={17}/></a></nav></div></header>
<main><section id="home" className="hero"><div className="heroGrid"/>{!mobile&&<GhostCursor color="#a855f7" trailLength={18} bloomStrength={0.13} maxDevicePixelRatio={0.45} zIndex={1}/>}<div className="container heroContent"><div className="heroText"><span className="status"><i/> DESENVOLVEDOR & CRIADOR DIGITAL</span><p className="index">PORTFÓLIO / 2026</p><h1>Ideias em<br/><em>código.</em><br/>Impacto <span>real.</span></h1><p className="lead">Sou <strong>Mateus Freitas</strong>. Desenvolvo sites, sistemas e experiências digitais que unem estética, movimento e funcionalidade.</p><div className="ctas"><a className="primary" href="#projetos">Explorar projetos <ArrowUpRight/></a><a className="secondary" href="#contato">Vamos criar juntos <ArrowRight/></a></div></div><div className="heroArtwork"><div className="violetOrb"><div className="orbCore"/></div><span className="floatingLabel">DESIGN × CODE × EXPERIENCE</span></div></div><span className="scrollHint">↓ SCROLL TO EXPLORE</span></section>
<div className="loop"><LogoLoop logos={skills.map(title=>({node:<span className="loopText">{title} <span>✦</span></span>,title}))} speed={65} gap={56} logoHeight={28} fadeOut fadeOutColor="#0b0810" pauseOnHover/></div>
<section id="sobre" className="section container"><div className="sectionHeader"><span className="eyebrow">01 — SOBRE MIM</span><h2>Construindo o<br/><span>extraordinário.</span></h2><p>Design não é só aparência. É transformar uma ideia em uma experiência útil, envolvente e memorável.</p></div><div className="aboutLayout"><ElectricBorder color="#9d54f8" speed={0.55} chaos={0.06} borderRadius={6}><article className="aboutCard"><span className="eyebrow">QUEM ESTÁ POR TRÁS DOS PROJETOS</span><h3>Olá, sou Mateus.</h3><p>Crio experiências digitais com identidade, movimento e propósito. Desenvolvo projetos para marcas e negócios, conectando interfaces modernas a funcionalidades reais.</p><p>De sites institucionais a dashboards com autenticação e gestão, cada solução nasce de um desafio diferente.</p><a href="#contato" className="textLink">Trabalhar comigo <ArrowUpRight/></a></article></ElectricBorder><div className="aboutVisual"><DitherVeil src="https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&q=85" fit="cover" palette="duotone" pattern="floyd" inkColor="#1b0a31" paperColor="#bb93ff" rimColor="#a855f7" rim={0.6} pixelSize={3} wander clickBurst/><span>INTERAJA COM A IMAGEM ↗</span></div></div></section>
<section id="servicos" className="section sectionDark"><div className="container"><div className="sectionHeader"><span className="eyebrow">02 — O QUE EU FAÇO</span><h2>Digital com<br/><span>personalidade.</span></h2><p>Um conjunto de soluções para transformar a presença digital do seu projeto.</p></div><div className="serviceGrid">{services.map(([title,desc,Icon],i)=><article className="serviceCard" key={title}><span className="serviceIndex">0{i+1}</span><Icon width={34} height={34} strokeWidth={1.4}/><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
<section id="projetos" className="section projectsSection container"><div className="sectionHeader"><span className="eyebrow">03 — TRABALHOS SELECIONADOS</span><h2>Projetos em<br/><span>destaque.</span></h2><p>Explore alguns dos projetos que desenvolvi. Arraste os cards para navegar pelo carrossel.</p></div><div className="carouselStage"><CircularCarousel items={projects.map(p=>({src:p.src,alt:p.title,title:p.title,subtitle:p.subtitle}))} preset="orbit" intro="assemble" autoplay="drift" cardWidth={mobile?160:260} aspectRatio={0.8} gap={34} speed={9} captions onItemClick={(item,index)=>window.open(projects[index]?.href,'_blank','noopener,noreferrer')}/></div><div className="projectGrid">{projects.map((p,i)=><a key={p.title} href={p.href} target="_blank" rel="noopener noreferrer" className="projectRow"><span className="projectNum">0{i+1}</span><span className="projectName">{p.title}</span><span className="projectDesc">{p.subtitle}</span><ArrowUpRight/></a>)}</div></section>
<section id="stack" className="section sectionDark"><div className="container"><div className="sectionHeader"><span className="eyebrow">04 — TECNOLOGIAS</span><h2>Design encontra<br/><span>tecnologia.</span></h2><p>Ferramentas para transformar conceitos em produtos reais.</p></div><div className="skillGrid">{skills.map((s,i)=><div className="skill" key={s}><span>0{String(i+1).padStart(2,'0')}</span><strong>{s}</strong><ArrowUpRight width={17}/></div>)}</div></div></section>
<section id="contato" className="contact section"><div className="container"><div className="eyebrow">05 — PRÓXIMO PROJETO</div><h2>Vamos criar<br/><span>algo incrível?</span></h2><p>Uma boa ideia merece sair do papel. Vamos conversar sobre a sua.</p><div className="ctas contactBtns"><a className="primary" href="mailto:mateusfreitas.business@gmail.com?subject=Novo%20projeto">Entre em contato <Mail/></a><a className="secondary" target="_blank" rel="noopener noreferrer" href="https://github.com/ZenithWe">Meu GitHub <Github/></a></div></div></section></main><footer><div className="container footer"><span>© {new Date().getFullYear()} Mateus Freitas</span><span>DESIGN. DEVELOPMENT. EXPERIENCE.</span><a href="#home">Voltar ao topo ↑</a></div></footer></>}
